from __future__ import annotations

from .identifiers import (
    BATTLE_SERVICE_STATIC,
    CAM_SPD_CONST,
    CAM_SPD_DEFAULT_NEW,
    CAM_SPD_DEFAULT_OLD,
    CLASS_CAM_BASE,
    CLASS_SPECTATOR_CAM,
    DRIVE_CTRL,
    FREECAM_ACTIVATE,
    FREECAM_DEACTIVATE,
    GROUND_CHK,
    GROUND_CHK_METHOD,
    PKG_CAM_BASE,
    PKG_CAM_SPECTATOR,
)

C_OLD = "      public static const §else catch if§:int = 5;\n"

C_NEW = (
    "      public static var _noclip_enabled_:Boolean = false;\n"
    "      public static var _noclip_full_:Boolean = false;\n"
    "      public static var _noclip_body_:* = null;\n"
    "      public static var _noclip_prev_x_:Number = 0;\n"
    "      public static var _noclip_prev_y_:Number = 0;\n"
    "      public static var _noclip_boost_:Boolean = false;\n"
    "      public static var _noclip_down_:Boolean = false;\n"
    "      public static var _noclip_hold_z_:Number = 0;\n"
    "      public static var _noclip_hold_active_:Boolean = false;\n"
    "      public static var _noclip_hold_snap_:Boolean = false;\n"
    "      public static var _noclip_fwd_:Boolean = false;\n"
    "      public static var _noclip_bwd_:Boolean = false;\n"
    "      public static var _noclip_lft_:Boolean = false;\n"
    "      public static var _noclip_rgt_:Boolean = false;\n"
    "      public static var _noclip_levelup_:Boolean = false;\n"
    "      public static var _freecam_active_:Boolean = false;\n"
    "      public static var _freecam_ctrl_:Object = null;\n"
    "      public static var _pickup_enabled_:Boolean = false;\n"
    "      public static var _pickup_retry_until_:Object = {};\n"
    "      public static var _beacon_enabled_:Boolean = true;\n"
    "      public static var _anti_afk_enabled_:Boolean = false;\n"
    "      public static var _anti_afk_last_input_:int = 0;\n"
    "      public static var _anti_afk_last_pulse_:int = 0;\n"
    "      public static var _anti_afk_pulse_until_:int = 0;\n"
    "      public static var _anti_afk_pulse_mask_:int = -1;\n"
    "      public static var _anti_afk_flip_:Boolean = false;\n"
    "\n"
    "      public static const §else catch if§:int = 5;\n"
)

E_OLD = (
    "         this.§5214237094237107123423632234§ = this.§521423111082311121123423632234§.§521423120402312053123423632234§(param1);\n"
    f"         if(this.{GROUND_CHK}.{GROUND_CHK_METHOD}())\n"
)

E_NEW = (
    "         this.§5214237094237107123423632234§ = this.§521423111082311121123423632234§.§521423120402312053123423632234§(param1);\n"
    f"         if(this.{GROUND_CHK}.{GROUND_CHK_METHOD}() || (_noclip_enabled_ && (_noclip_boost_ || _noclip_hold_active_)) || _noclip_full_)\n"
)

G_OLD = (
    f"      private static const {CAM_SPD_CONST}:ConsoleVarFloat = new ConsoleVarFloat(\"cam_spd\",{CAM_SPD_DEFAULT_OLD},0,10000);\n"
)

G_NEW = (
    f"      private static const {CAM_SPD_CONST}:ConsoleVarFloat = new ConsoleVarFloat(\"cam_spd\",{CAM_SPD_DEFAULT_NEW},0,10000);\n"
)

D_OLD = (
    "         var _loc2_:int = 0;\n"
    "         var _loc5_:GameActionEnum = §extends package override§.getBindingAction(param1.keyCode,false);\n"
    "         if(!_loc5_)\n"
    "         {\n"
    "            return;\n"
    "         }\n"
    "         var _loc4_:int = §const var import§;\n"
    "         var _loc3_:Boolean = param1.type == \"keyDown\";\n"
    "         switch(_loc5_)\n"
)

D_NEW = (
    "         var _loc2_:int = 0;\n"
    "         var _loc5_:GameActionEnum = §extends package override§.getBindingAction(param1.keyCode,false);\n"
    "         if(param1.type == \"keyDown\" || param1.type == \"keyUp\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._anti_afk_last_input_ = getTimer();\n"
    "         }\n"
    "         if(param1.keyCode == 118 && param1.type == \"keyDown\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._freecam_active_ = !{DRIVE_CTRL}._freecam_active_;\n"
    f"            if({DRIVE_CTRL}._freecam_active_)\n"
    "            {\n"
    f"               var _spectator_:* = new {PKG_CAM_SPECTATOR}.{CLASS_SPECTATOR_CAM}();\n"
    f"               {DRIVE_CTRL}._freecam_ctrl_ = _spectator_;\n"
    f"               _spectator_.{FREECAM_ACTIVATE}();\n"
    f"               {DRIVE_CTRL}._noclip_fwd_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_bwd_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_lft_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_rgt_ = false;\n"
    "               §521423127992312812123423632234§(this.§set use super§);\n"
    "            }\n"
    "            else\n"
    "            {\n"
    f"               if({DRIVE_CTRL}._freecam_ctrl_ != null)\n"
    "               {\n"
    f"                  {DRIVE_CTRL}._freecam_ctrl_.{FREECAM_DEACTIVATE}();\n"
    f"                  {PKG_CAM_BASE}.{CLASS_CAM_BASE}.{BATTLE_SERVICE_STATIC}.setFollowCamera();\n"
    "               }\n"
    f"               {DRIVE_CTRL}._freecam_ctrl_ = null;\n"
    f"               {DRIVE_CTRL}._noclip_fwd_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_bwd_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_lft_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_rgt_ = false;\n"
    "               §521423127992312812123423632234§(this.§set use super§);\n"
    "            }\n"
    "            return;\n"
    "         }\n"
    "         if(param1.keyCode == 119 && param1.type == \"keyDown\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._noclip_enabled_ = !{DRIVE_CTRL}._noclip_enabled_;\n"
    f"            if(!{DRIVE_CTRL}._noclip_enabled_)\n"
    "            {\n"
    f"               {DRIVE_CTRL}._noclip_full_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_hold_active_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_hold_snap_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_boost_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_down_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_levelup_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_fwd_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_bwd_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_lft_ = false;\n"
    f"               {DRIVE_CTRL}._noclip_rgt_ = false;\n"
    "            }\n"
    "         }\n"
    "         if(param1.keyCode == 116 && param1.type == \"keyDown\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._beacon_enabled_ = !{DRIVE_CTRL}._beacon_enabled_;\n"
    "         }\n"
    "         if(param1.keyCode == 117 && param1.type == \"keyDown\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._pickup_enabled_ = !{DRIVE_CTRL}._pickup_enabled_;\n"
    "         }\n"
    "         if(param1.keyCode == 121 && param1.type == \"keyDown\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._anti_afk_enabled_ = !{DRIVE_CTRL}._anti_afk_enabled_;\n"
    f"            {DRIVE_CTRL}._anti_afk_last_input_ = getTimer();\n"
    f"            {DRIVE_CTRL}._anti_afk_last_pulse_ = 0;\n"
    f"            {DRIVE_CTRL}._anti_afk_pulse_until_ = 0;\n"
    f"            {DRIVE_CTRL}._anti_afk_pulse_mask_ = -1;\n"
    f"            {DRIVE_CTRL}._anti_afk_flip_ = false;\n"
    "         }\n"
    f"         if({DRIVE_CTRL}._noclip_enabled_)\n"
    "         {\n"
    "            if(param1.keyCode == 17)\n"
    "            {\n"
    f"               {DRIVE_CTRL}._noclip_boost_ = param1.type == \"keyDown\";\n"
    "            }\n"
    "            if(param1.keyCode == 16)\n"
    "            {\n"
    f"               {DRIVE_CTRL}._noclip_down_ = param1.type == \"keyDown\";\n"
    "            }\n"
    "            if(param1.keyCode == 192 && param1.type == \"keyDown\")\n"
    "            {\n"
    f"               {DRIVE_CTRL}._noclip_hold_active_ = !{DRIVE_CTRL}._noclip_hold_active_;\n"
    f"               {DRIVE_CTRL}._noclip_full_ = {DRIVE_CTRL}._noclip_hold_active_;\n"
    f"               if({DRIVE_CTRL}._noclip_hold_active_)\n"
    "               {\n"
    f"                  {DRIVE_CTRL}._noclip_hold_snap_ = true;\n"
    "               }\n"
    "            }\n"
    "            if(param1.keyCode == 82)\n"
    "            {\n"
    f"               {DRIVE_CTRL}._noclip_levelup_ = param1.type == \"keyDown\";\n"
    "            }\n"
    "         }\n"
    "         else if(param1.type == \"keyUp\")\n"
    "         {\n"
    f"            {DRIVE_CTRL}._noclip_boost_ = false;\n"
    f"            {DRIVE_CTRL}._noclip_down_ = false;\n"
    f"            {DRIVE_CTRL}._noclip_levelup_ = false;\n"
    "         }\n"
    "         if(!_loc5_)\n"
    "         {\n"
    "            return;\n"
    "         }\n"
    "         var _loc4_:int = §const var import§;\n"
    "         var _loc3_:Boolean = param1.type == \"keyDown\";\n"
    f"         if({DRIVE_CTRL}._freecam_active_ && (_loc5_ == GameActionEnum.CHASSIS_FORWARD_MOVEMENT || _loc5_ == GameActionEnum.CHASSIS_BACKWARD_MOVEMENT || _loc5_ == GameActionEnum.CHASSIS_LEFT_MOVEMENT || _loc5_ == GameActionEnum.CHASSIS_RIGHT_MOVEMENT))\n"
    "         {\n"
    "            if(§const var import§ != this.§set use super§)\n"
    "            {\n"
    "               §521423127992312812123423632234§(this.§set use super§);\n"
    "            }\n"
    "            return;\n"
    "         }\n"
    "         if(_loc5_ == GameActionEnum.CHASSIS_FORWARD_MOVEMENT)\n"
    "         {\n"
    f"            {DRIVE_CTRL}._noclip_fwd_ = _loc3_;\n"
    "         }\n"
    "         if(_loc5_ == GameActionEnum.CHASSIS_BACKWARD_MOVEMENT)\n"
    "         {\n"
    f"            {DRIVE_CTRL}._noclip_bwd_ = _loc3_;\n"
    "         }\n"
    "         if(_loc5_ == GameActionEnum.CHASSIS_LEFT_MOVEMENT)\n"
    "         {\n"
    f"            {DRIVE_CTRL}._noclip_lft_ = _loc3_;\n"
    "         }\n"
    "         if(_loc5_ == GameActionEnum.CHASSIS_RIGHT_MOVEMENT)\n"
    "         {\n"
    f"            {DRIVE_CTRL}._noclip_rgt_ = _loc3_;\n"
    "         }\n"
    "         switch(_loc5_)\n"
)
