from __future__ import annotations

from .identifiers import (
    AIR_TURN_SPEED,
    ANGULAR_VEL,
    ANTI_FLIP_THRESHOLD,
    BATTLE_SERVICE_STATIC,
    BODY_FIELD,
    BODY_STATE,
    BODY_WRAPPER,
    BONUS_REGISTRY_FIELD,
    CLIENT_TANK_FIELD,
    DRIVE_CTRL,
    FILE_B,
    HOLD_DAMP,
    LEVEL_DAMP,
    LEVEL_SPEED,
    LINEAR_VEL,
    PICKUP_RADIUS,
    PICKUP_RETRY_MS,
    PKG_BONUS_COMMON,
    POS_FIELD,
    QUAT_FIELD,
    BOOST_SPEED,
    TANK_SPEC_FIELD,
)

B_OLD = (
    "      public function runAfterPhysicsUpdate(param1:Number) : void\n"
    "      {\n"
    "         this.§dynamic for var§();\n"
    "         this.§break finally function§.§5214234287234300123423632234§();\n"
    "         this.§finally continue§.§package catch class§(this.§break switch catch§());\n"
    "      }"
)

B_NEW = (
    "      public function runAfterPhysicsUpdate(param1:Number) : void\n"
    "      {\n"
    "         this.§dynamic for var§();\n"
    "         this.§break finally function§.§5214234287234300123423632234§();\n"
    "         this.§finally continue§.§package catch class§(this.§break switch catch§());\n"
    "         if(this.local)\n"
    "         {\n"
    f"            var _bs_:* = this.{BODY_WRAPPER}.{BODY_FIELD}.{BODY_STATE};\n"
    f"            {DRIVE_CTRL}._noclip_body_ = this.{BODY_WRAPPER}.{BODY_FIELD};\n"
    f"            var _cx_:Number = _bs_.{POS_FIELD}.x;\n"
    f"            var _cy_:Number = _bs_.{POS_FIELD}.y;\n"
    f"            var _dxy2_:Number = (_cx_ - {DRIVE_CTRL}._noclip_prev_x_) * (_cx_ - {DRIVE_CTRL}._noclip_prev_x_) + (_cy_ - {DRIVE_CTRL}._noclip_prev_y_) * (_cy_ - {DRIVE_CTRL}._noclip_prev_y_);\n"
    f"            {DRIVE_CTRL}._noclip_prev_x_ = _cx_;\n"
    f"            {DRIVE_CTRL}._noclip_prev_y_ = _cy_;\n"
    f"            if({DRIVE_CTRL}._pickup_enabled_)\n"
    "            {\n"
    f"               var _bsvc2_:* = {PKG_BONUS_COMMON}.BonusCommonModel.{BATTLE_SERVICE_STATIC};\n"
    "               if(_bsvc2_ != null)\n"
    "               {\n"
    f"                  var _reg_:* = _bsvc2_.{BONUS_REGISTRY_FIELD};\n"
    "                  if(_reg_ != null)\n"
    "                  {\n"
    f"                     var _myX_:Number = _bs_.{POS_FIELD}.x;\n"
    f"                     var _myY_:Number = _bs_.{POS_FIELD}.y;\n"
    "                     var _nowPhys_:int = _bsvc2_.getPhysicsTime();\n"
    "                     for(var _bk_:* in _reg_.bonuses)\n"
    "                     {\n"
    "                        var _bo_:* = _reg_.bonuses[_bk_];\n"
    "                        if(_bo_ == null) continue;\n"
    "                        var _bmesh_:* = _bo_.getBonusMesh();\n"
    "                        if(_bmesh_ == null) continue;\n"
    "                        var _dx_:Number = _bmesh_.object.x - _myX_;\n"
    "                        var _dy_:Number = _bmesh_.object.y - _myY_;\n"
    f"                        if(_dx_*_dx_ + _dy_*_dy_ < {PICKUP_RADIUS * PICKUP_RADIUS})\n"
    "                        {\n"
    f"                           var _nextTry_:* = {DRIVE_CTRL}._pickup_retry_until_[_bk_];\n"
    "                           if(_nextTry_ == null || _nowPhys_ >= int(_nextTry_))\n"
    "                           {\n"
    "                              _bsvc2_.onTankCollision(_bo_);\n"
    f"                              {DRIVE_CTRL}._pickup_retry_until_[_bk_] = _nowPhys_ + {PICKUP_RETRY_MS};\n"
    "                           }\n"
    "                        }\n"
    "                        else\n"
    "                        {\n"
    f"                           delete {DRIVE_CTRL}._pickup_retry_until_[_bk_];\n"
    "                        }\n"
    "                     }\n"
    "                  }\n"
    "               }\n"
    "            }\n"
    f"            if({DRIVE_CTRL}._freecam_active_)\n"
    "            {\n"
    f"               _bs_.{LINEAR_VEL}.x = 0;\n"
    f"               _bs_.{LINEAR_VEL}.y = 0;\n"
    f"               _bs_.{LINEAR_VEL}.z = 0;\n"
    f"               _bs_.{ANGULAR_VEL}.x = 0;\n"
    f"               _bs_.{ANGULAR_VEL}.y = 0;\n"
    f"               _bs_.{ANGULAR_VEL}.z = 0;\n"
    "               return;\n"
    "            }\n"
    f"            if(!{DRIVE_CTRL}._noclip_enabled_ && !{DRIVE_CTRL}._noclip_full_)\n"
    "            {\n"
    "               return;\n"
    "            }\n"
    f"            var _aflq_:* = _bs_.{QUAT_FIELD};\n"
    "            var _afpe_:Number = 2.0 * (_aflq_.w * _aflq_.x - _aflq_.y * _aflq_.z);\n"
    "            var _afre_:Number = 2.0 * (_aflq_.w * _aflq_.y + _aflq_.x * _aflq_.z);\n"
    f"            if(Math.abs(_afpe_) > {ANTI_FLIP_THRESHOLD} && _afpe_ * _bs_.{ANGULAR_VEL}.x > 0)\n"
    "            {\n"
    f"               _bs_.{ANGULAR_VEL}.x = 0;\n"
    "            }\n"
    f"            if(Math.abs(_afre_) > {ANTI_FLIP_THRESHOLD} && _afre_ * _bs_.{ANGULAR_VEL}.y > 0)\n"
    "            {\n"
    f"               _bs_.{ANGULAR_VEL}.y = 0;\n"
    "            }\n"
    f"            if({DRIVE_CTRL}._noclip_levelup_)\n"
    "            {\n"
    f"               var _lq_:* = _bs_.{QUAT_FIELD};\n"
    "               var _pe_:Number = 2 * (_lq_.w * _lq_.x - _lq_.y * _lq_.z);\n"
    "               var _re_:Number = 2 * (_lq_.w * _lq_.y + _lq_.x * _lq_.z);\n"
    f"               _bs_.{ANGULAR_VEL}.x = -_pe_ * {LEVEL_SPEED};\n"
    f"               _bs_.{ANGULAR_VEL}.y = -_re_ * {LEVEL_SPEED};\n"
    f"               _bs_.{LINEAR_VEL}.x = _bs_.{LINEAR_VEL}.x * {LEVEL_DAMP};\n"
    f"               _bs_.{LINEAR_VEL}.y = _bs_.{LINEAR_VEL}.y * {LEVEL_DAMP};\n"
    f"               _bs_.{LINEAR_VEL}.z = _bs_.{LINEAR_VEL}.z * {LEVEL_DAMP};\n"
    "            }\n"
    f"            if({DRIVE_CTRL}._noclip_boost_)\n"
    "            {\n"
    f"               _bs_.{LINEAR_VEL}.z = {BOOST_SPEED};\n"
    f"               if({DRIVE_CTRL}._noclip_hold_active_)\n"
    "               {\n"
    f"                  {DRIVE_CTRL}._noclip_hold_z_ = _bs_.{POS_FIELD}.z;\n"
    "               }\n"
    "            }\n"
    f"            else if({DRIVE_CTRL}._noclip_down_)\n"
    "            {\n"
    f"               _bs_.{LINEAR_VEL}.z = -{BOOST_SPEED};\n"
    f"               if({DRIVE_CTRL}._noclip_hold_active_)\n"
    "               {\n"
    f"                  {DRIVE_CTRL}._noclip_hold_z_ = _bs_.{POS_FIELD}.z;\n"
    "               }\n"
    "            }\n"
    f"            else if({DRIVE_CTRL}._noclip_full_)\n"
    "            {\n"
    f"               if({DRIVE_CTRL}._noclip_hold_snap_ || _dxy2_ > 250000)\n"
    "               {\n"
    f"                  {DRIVE_CTRL}._noclip_hold_z_ = _bs_.{POS_FIELD}.z;\n"
    f"                  {DRIVE_CTRL}._noclip_hold_snap_ = false;\n"
    "               }\n"
    f"               var _err_:Number = {DRIVE_CTRL}._noclip_hold_z_ - _bs_.{POS_FIELD}.z;\n"
    "               if(_err_ > 0)\n"
    "               {\n"
    f"                  _bs_.{LINEAR_VEL}.z = Math.min(_err_ * 30, 500);\n"
    "               }\n"
    "               else\n"
    "               {\n"
    f"                  _bs_.{LINEAR_VEL}.z = 0;\n"
    "               }\n"
    f"               var _flq_:* = _bs_.{QUAT_FIELD};\n"
    "               var _fpe_:Number = 2 * (_flq_.w * _flq_.x - _flq_.y * _flq_.z);\n"
    "               var _fre_:Number = 2 * (_flq_.w * _flq_.y + _flq_.x * _flq_.z);\n"
    f"               _bs_.{ANGULAR_VEL}.x = -_fpe_ * {LEVEL_SPEED};\n"
    f"               _bs_.{ANGULAR_VEL}.y = -_fre_ * {LEVEL_SPEED};\n"
    f"               if(!{DRIVE_CTRL}._noclip_fwd_ && !{DRIVE_CTRL}._noclip_bwd_)\n"
    "               {\n"
    f"                  _bs_.{LINEAR_VEL}.x = _bs_.{LINEAR_VEL}.x * {HOLD_DAMP};\n"
    f"                  _bs_.{LINEAR_VEL}.y = _bs_.{LINEAR_VEL}.y * {HOLD_DAMP};\n"
    "               }\n"
    "            }\n"
    f"            else if({DRIVE_CTRL}._noclip_hold_active_)\n"
    "            {\n"
    f"               if({DRIVE_CTRL}._noclip_hold_snap_)\n"
    "               {\n"
    f"                  {DRIVE_CTRL}._noclip_hold_z_ = _bs_.{POS_FIELD}.z;\n"
    f"                  {DRIVE_CTRL}._noclip_hold_snap_ = false;\n"
    "               }\n"
    f"               if(_bs_.{POS_FIELD}.z < {DRIVE_CTRL}._noclip_hold_z_ && _bs_.{LINEAR_VEL}.z <= 0)\n"
    "               {\n"
    f"                  _bs_.{LINEAR_VEL}.z = 50;\n"
    "               }\n"
    f"               if(!{DRIVE_CTRL}._noclip_fwd_ && !{DRIVE_CTRL}._noclip_bwd_)\n"
    "               {\n"
    f"                  _bs_.{LINEAR_VEL}.x = _bs_.{LINEAR_VEL}.x * {HOLD_DAMP};\n"
    f"                  _bs_.{LINEAR_VEL}.y = _bs_.{LINEAR_VEL}.y * {HOLD_DAMP};\n"
    "               }\n"
    "            }\n"
    f"            var _q_:* = _bs_.{QUAT_FIELD};\n"
    "            var _fwdX_:Number = 2 * (_q_.x * _q_.y - _q_.w * _q_.z);\n"
    "            var _fwdY_:Number = 1 - 2 * (_q_.x * _q_.x + _q_.z * _q_.z);\n"
    f"            var _maxSpd_:Number = BattleUtils.toClientScale(this.{CLIENT_TANK_FIELD}.{TANK_SPEC_FIELD}.speed);\n"
    f"            if({DRIVE_CTRL}._noclip_fwd_)\n"
    "            {\n"
    f"               _bs_.{LINEAR_VEL}.x = _fwdX_ * _maxSpd_;\n"
    f"               _bs_.{LINEAR_VEL}.y = _fwdY_ * _maxSpd_;\n"
    "            }\n"
    f"            else if({DRIVE_CTRL}._noclip_bwd_)\n"
    "            {\n"
    f"               _bs_.{LINEAR_VEL}.x = -_fwdX_ * _maxSpd_;\n"
    f"               _bs_.{LINEAR_VEL}.y = -_fwdY_ * _maxSpd_;\n"
    "            }\n"
    f"            if({DRIVE_CTRL}._noclip_lft_)\n"
    "            {\n"
    f"               _bs_.{ANGULAR_VEL}.z = {AIR_TURN_SPEED};\n"
    "            }\n"
    f"            else if({DRIVE_CTRL}._noclip_rgt_)\n"
    "            {\n"
    f"               _bs_.{ANGULAR_VEL}.z = -{AIR_TURN_SPEED};\n"
    "            }\n"
    "            else\n"
    "            {\n"
    f"               _bs_.{ANGULAR_VEL}.z = 0;\n"
    "            }\n"
    "         }\n"
    "      }\n"
)